export APPD_CONTROLER_URL="http://xxx"
export APPD_CONTROLLER_PORT="8090"
export APPD_EUM_PORT="9080"
export APPD_API_TOKEN=""
export APPD_ANALYTICS_API_TOKEN=""
export APPD_SNAPSHOT_PERIODS_MIN="15"
export APPD_GLOBAL_ACCOUNT_NAME=""
export APPD_APPLICATION_NAME=""

